# Generated by Django 2.0 on 2018-04-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='age',
            new_name='sex',
        ),
    ]
